= Gatling JSF demo

This sample app just shows how to execute JSF requests through http://gatling.io/#/[Gatling stress tool] against http://www.primefaces.org/showcase/[Primefaces showcase^].

== Running it

----
mvn gatling:execute
----

== Example

The only difference when working with JSF is that you need to handle the http://stackoverflow.com/questions/2910741/what-is-viewstate-in-jsf-and-how-is-it-used[Viewstate^] which basically stores components state.

So the essence of this demo is the http://gatling.io/docs/2.1.6/http/http_check.html[Gatling checks] for viewstate:

[source, scala]
----
  val jsfViewStateCheck = css("input[name='javax.faces.ViewState']", "value")
    .saveAs("viewState")

  val jsfPartialViewStateCheck = xpath("//update[contains(@id,'ViewState')]")
    .saveAs("viewState")
----

and here the template requests that calls the checks:

[source, scala]
----
def jsfGet(name: String, url: Expression[String]) =
    http(name)
      .get(url)
      .check(jsfViewStateCheck)

  def jsfPost(name: String, url: Expression[String]) = http(name)
    .post(url)
    .formParam("javax.faces.ViewState", "${viewState}")
    .check(jsfViewStateCheck)

  def jsfPartialPost(name: String, url: Expression[String]) = http(name)
    .post(url)
    .header("Faces-Request", "partial/ajax") <1>
    .formParam("javax.faces.partial.ajax", "true") <1>
    .formParam("javax.faces.ViewState", "${viewState}") <2>
    .check(jsfPartialViewStateCheck)
----

<1> JSF ajax call indication, JSF will return a xml in the response
<2> already stored (in gatling session) view state

So we basically have two kinds of request, a _normal_ and a _partial_ http request. Partial requests are mainly to deal with ajax calls (e.g p:ajax or f:ajax).

IMPORTANT: As you can see the *viewState* has already been stored in gatling session on a previous request so basically a *jsfGet* call has already been made.

Here is a JSF ajax button call:

----
 <p:commandButton value="Ajax Submit" id="ajax" update="growl" actionListener="#{buttonView.buttonAction}" styleClass="ui-priority-primary" />
----

NOTE: This code is taken from Primefaces showcase: http://www.primefaces.org/showcase/ui/button/commandButton.xhtml[http://www.primefaces.org/showcase/ui/button/commandButton.xhtml^]

and here is the correspondent Gatling call:

[source, scala]
----
def ajaxButtonCall = jsfPartialPost("request_ajax_button", "/ui/button/commandButton.xhtml")
    .formParam("javax.faces.source", "${btAjax}")
    .formParam("javax.faces.partial.execute", "@all")
    .formParam("${btAjax}", "${btAjax}")
    .formParam("${form}", "${form}")
    .check(status.is(200))
----

As state before we need a previous JSF call to store button id (*${btAjax}*), form id (*${form}*) and *viewState* in session, here is the *initial* call, it just GETs the page:

[source, scala]
----
 jsfGet("saveState", "/ui/button/commandButton.xhtml")
        .check(status.is(200), ajaxButtonIdCheck, formIdCheck)
----

here is checks that stores the component ids in Gatling session:

----
  val ajaxButtonIdCheck = css("button[id$='ajax']", "id")
    .saveAs("btAjax")

  val formIdCheck = css("form", "id")
    .saveAs("form")
----

== Ajax Behaviour event

For ajax behaviour event the approach is quite similar, here goes an example of *keyup* event on page http://www.primefaces.org/showcase/ui/ajax/event.xhtml[http://www.primefaces.org/showcase/ui/ajax/event.xhtml^]:

.com.rmpestano.gatling.perf.AjaxEventSimulation
[source,scala]
----
  val formIdCheck = css("form", "id")
    .saveAs("form")

  val inputIdCheck = css("input[id$='firstname']", "id")
    .saveAs("inputId") //stores in gatling session id of input with id that endswith 'firstname'

  val outputIdCheck = css("span[id$='out1']", "id")
    .saveAs("outputId")

  //checks the partial response xml result
    val outputValueCheck = xpath("//*[@id, contains(@id,'out1') and @value ='Gatling, JSF and Primefaces rules']")
    .saveAs("outputValue")

    def ajaxEventRequest = jsfPartialPost("request_ajax_event", "/ui/ajax/event.xhtml")
        .formParam("javax.faces.source", "${inputId}")
        .formParam("javax.faces.partial.execute", "${inputId}")
        .formParam("javax.faces.behavior.event", "keyup")
        .formParam("javax.faces.partial.event", "keyup")
        .formParam("javax.faces.partial.render","${outputId}")
        .formParam("${inputId}", "Gatling, JSF and Primefaces rules")
        .formParam("${form}", "${form}")
        .check(status.is(200), outputValueCheck)

    val AjaxEventScenario = scenario("ajaxEvent scenario")
       .exec(
         jsfGet("initialRequest", "/ui/ajax/event.xhtml")
           .check(status.is(200), inputIdCheck,outputIdCheck, formIdCheck)
       )
       .pause(2)
       .exec(ajaxEventRequest)
       .pause(1)
----

here is Gatling response to confirm the partial event is fired:

----
<partial-response id="j_id1"><changes><update id="j_idt87:out1"><![CDATA[<span id="j_idt87:out1">Gatling, JSF and Primefaces rules</span>]]></update><update id="j_id1:javax.faces.ViewState:0"><![CDATA[5642006804874081440:6246997700145170162]]></update></changes></partial-response>
----

== Test Result

the output should be something like this:

----
---- Global Information --------------------------------------------------------
> request count                                        208 (OK=208    KO=0     )
> min response time                                    230 (OK=230    KO=-     )
> max response time                                   3317 (OK=3317   KO=-     )
> mean response time                                   436 (OK=436    KO=-     )
> std deviation                                        436 (OK=436    KO=-     )
> response time 50th percentile                        249 (OK=249    KO=-     )
> response time 75th percentile                        390 (OK=390    KO=-     )
> mean requests/sec                                  15.81 (OK=15.81  KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                           182 ( 88%)
> 800 ms < t < 1200 ms                                  10 (  5%)
> t > 1200 ms                                           16 (  8%)
> failed                                                 0 (  0%)
================================================================================

Reports generated in 1s.
Please open the following file: /home/pestano/projects/gatling-jsf-demo/target/gatling/results/commandbuttonsimulation-1431729180680/index.html
Global: percentage of successful requests is greater than 95 : true
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.186s
[INFO] Finished at: Fri May 15 19:33:15 BRT 2015
[INFO] Final Memory: 7M/150M
[INFO] ------------------------------------------------------------------------
----




